apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-script
data:
  script.sh: |
    oc login --token=$()
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: users-read-only-workspace
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: set-permissions
              image: quay.io/aminerachyd/ibmcloud-dev:latest
              command:
                - /bin/sh
                - -c
                - /home/script/script.sh
              volumeMounts:
                - name: script
                  mountPath: "/home/script/"
          volumes:
            - name: script
              configMap:
                name: cronjob-script
                defaultMode: 0777
          restartPolicy: OnFailure
