apiVersion: v1
kind: ServiceAccount
metadata:
  name: configure-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configure-users-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: configure-users
  namespace: techzone-boutique-dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-script
data:
  script.sh: |
    oc login --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) --server=kubernetes.default.svc --insecure-skip-tls-verify
    set -x
    oc patch group techzone-multiarch-demo --patch {\"users\":$(oc get users -o json | jq -c ' .items | map(select( .identities[0] | contains("IBMid") )) | map(.metadata.name) ')}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: users-read-only-workspace
spec:
  ## Every 5 minutes
  #schedule: "*/5 * * * *"
  ## Every minute
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: configure-users
          containers:
            - name: set-permissions
              image: quay.io/aminerachyd/ibmcloud-dev:latest
              command:
                - /bin/sh
                - -c
                - /home/script/script.sh
              volumeMounts:
                - name: script
                  mountPath: "/home/script/"
          volumes:
            - name: script
              configMap:
                name: cronjob-script
                defaultMode: 0777
          restartPolicy: OnFailure
