apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: techzone-multiarch-demo-grp
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-volsync-namespace
        spec:
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  annotations:
                    openshift.io/description: A user that can request projects.
                    rbac.authorization.kubernetes.io/autoupdate: "true"
                  name: self-provisioner
                rules:
                  - apiGroups:
                      - ""
                      - project.openshift.io
                    resources:
                      - projectrequests
                    verbs:
                      - create
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: user.openshift.io/v1
                kind: Group
                metadata:
                  name: techzone-multiarch-demo
                users:
                  {{- range .Values.users }}
                  - {{.}}
                  {{- end }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: view-techzone-dev-project
                  namespace: techzone-boutique-dev
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
                subjects:
                  - apiGroup: rbac.authorization.k8s.io
                    kind: Group
                    name: techzone-multiarch-demo
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: view-techzone-test-project
                  namespace: techzone-boutique-test
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
                subjects:
                  - apiGroup: rbac.authorization.k8s.io
                    kind: Group
                    name: techzone-multiarch-demo
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding
                metadata:
                  name: view-techzone-prod-project
                  namespace: techzone-boutique-prod
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
                subjects:
                  - apiGroup: rbac.authorization.k8s.io
                    kind: Group
                    name: techzone-multiarch-demo
          remediationAction: enforce
          severity: high
  remediationAction: enforce
